'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Front window is not a mapper..
        '''</summary>
        Friend ReadOnly Property ERR_FRONT_WIN_NOT_MAPPER() As String
            Get
                Return ResourceManager.GetString("ERR_FRONT_WIN_NOT_MAPPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid XML.
        '''</summary>
        Friend ReadOnly Property ERR_INVALID_XML() As String
            Get
                Return ResourceManager.GetString("ERR_INVALID_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to display the dialog..
        '''</summary>
        Friend ReadOnly Property ERR_MB_DLG_NOT_DISPLAYED() As String
            Get
                Return ResourceManager.GetString("ERR_MB_DLG_NOT_DISPLAYED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2000;PROJCS[&quot;Anguilla 1957 / British West Indies Grid&quot;,GEOGCS[&quot;Anguilla 1957&quot;,DATUM[&quot;Anguilla_1957&quot;,SPHEROID[&quot;Clarke 1880 (RGS)&quot;,6378249.145,293.465,AUTHORITY[&quot;EPSG&quot;,&quot;7012&quot;]],AUTHORITY[&quot;EPSG&quot;,&quot;6600&quot;]],PRIMEM[&quot;Greenwich&quot;,0,AUTHORITY[&quot;EPSG&quot;,&quot;8901&quot;]],UNIT[&quot;degree&quot;,0.01745329251994328,AUTHORITY[&quot;EPSG&quot;,&quot;9122&quot;]],AUTHORITY[&quot;EPSG&quot;,&quot;4600&quot;]],PROJECTION[&quot;Transverse_Mercator&quot;],PARAMETER[&quot;latitude_of_origin&quot;,0],PARAMETER[&quot;central_meridian&quot;,-62],PARAMETER[&quot;scale_factor&quot;,0.9995],PARAMETER[&quot;false_easting&quot;,400000],PARAMETER [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SRID() As String
            Get
                Return ResourceManager.GetString("SRID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About {0}.
        '''</summary>
        Friend ReadOnly Property STR_ABOUT() As String
            Get
                Return ResourceManager.GetString("STR_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This application draws profile from grids recognised by the native MapInfo Grid handler.
        '''</summary>
        Friend ReadOnly Property STR_ABT_DESC1() As String
            Get
                Return ResourceManager.GetString("STR_ABT_DESC1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Draw a profile over an MI grid to view elevation data. (MI recognises asc,grd,mig,adf,img and a few other obscure formats).
        '''</summary>
        Friend ReadOnly Property STR_ABT_DESC2() As String
            Get
                Return ResourceManager.GetString("STR_ABT_DESC2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Folder.
        '''</summary>
        Friend ReadOnly Property STR_DEF_FOLDER_NAME() As String
            Get
                Return ResourceManager.GetString("STR_DEF_FOLDER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MapInfoPhotoGPSPlotter.
        '''</summary>
        Friend ReadOnly Property STR_MB_APP_DESC() As String
            Get
                Return ResourceManager.GetString("STR_MB_APP_DESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MapInfoPhotoGPSPlotter.MBX.
        '''</summary>
        Friend ReadOnly Property STR_MB_APP_FILENAME() As String
            Get
                Return ResourceManager.GetString("STR_MB_APP_FILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MapInfoPhotoGPSPlotter.
        '''</summary>
        Friend ReadOnly Property STR_MB_BTN_PAD_HLPMSG() As String
            Get
                Return ResourceManager.GetString("STR_MB_BTN_PAD_HLPMSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools.
        '''</summary>
        Friend ReadOnly Property STR_MB_BTN_PAD_TOOLS() As String
            Get
                Return ResourceManager.GetString("STR_MB_BTN_PAD_TOOLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;About MapInfoPhotoGPSPlotter....
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_ABOUT() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xit MapInfoPhotoGPSPlotter.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_EXIT() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;MapInfoPhotoGPSPlotter.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_PROFILETOOL() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_PROFILETOOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;MapInfoPhotoGPSPlotter.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_SUBTITLE() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_SUBTITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center = ({0}, {1}) - Zoom = {2} {3}.
        '''</summary>
        Friend ReadOnly Property STR_TOOLTIP_VIEW() As String
            Get
                Return ResourceManager.GetString("STR_TOOLTIP_VIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0}.
        '''</summary>
        Friend ReadOnly Property STR_VERSION() As String
            Get
                Return ResourceManager.GetString("STR_VERSION", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
